web:
  build: .
  command: python -u autoapp.py
  environment:
    - GOOGLE_APPLICATION_CREDENTIALS=key.json
  ports:
    - "5000:5000"
  volumes:
    - .:/pajamas
  links:
    - db
db:
  image: mongo:4.4.1